CC := $(CROSS_COMPILE)gcc
CFLAGS := -Wall -Werror

TARGET := writer
SRC := writer.c
OBJ := writer.o

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^

$(OBJ): $(SRC)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(TARGET) *.o

.PHONY: all clean
